name: permitlog
description: A simple app to help learner&#x27;s permit holders track their driving.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  flutter_markdown: ^0.2.0
  url_launcher: ^3.0.1
  google_sign_in: ^3.0.4
  firebase_auth: ^0.5.12
  firebase_database: ^1.0.1
  intl: ^0.15.6
  flutter_facebook_login: ^1.1.1
  shared_preferences: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

test:

flutter:
  uses-material-design: true
  assets:
    - assets/states.json