name: permitlog
description: A simple app to help learner&#x27;s permit holders track their driving.

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^3.0.0
  cupertino_icons: ^0.1.0
  firebase_auth: 0.2.0
  firebase_database: 0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true