name: permitlog
description: A simple app to help learner&#x27;s permit holders track their driving.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.0
  flutter_markdown: ^0.1.5
  url_launcher: ^3.0.1
  google_sign_in: ^3.0.4
  firebase_auth: ^0.5.11
  firebase_database: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true